version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8080"
  db:
    image: "postgres"
    environment:
      POSTGRES_USER: HilmiFaww
      POSTGRES_DB: template1
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432